name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
      - name: Install dependencies
        run: |
          apk add build-base git zip

      - uses: actions/checkout@v2
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --prune --unshallow

      - name: Install libsmb
        run: |
           git clone https://github.com/sahlberg/libsmb2.git
           cd libsmb2/lib 
           make install clean -f Makefile.PS2_EE 

      - name: Install libnfs
        run: |
          git clone https://github.com/sahlberg/libnfs.git
          cd libnfs/ps2_ee
          make install clean -f Makefile.PS2_EE

      - name: Compile wLaunchELF
        run: |
          make
          git ls-files -i --exclude-standard -c

      - name: Get short SHA
        id: slug
        run: echo "{sha8}={$(echo ${GITHUB_SHA} | cut -c1-8)}" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: wLaunchELF-${{ steps.slug.outputs.sha8 }}
          path: BOOT.ELF

      - name: Create release
        if: github.ref == 'refs/heads/master'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Latest development build"
          files: BOOT.ELF
